import Head from "next/head";
import Footer from "../components/footer/footer";
import Header from "../components/header/header";
import InfoDashBoard from "../components/infoDashboard/infoDashboard";
import SideBar from "../components/sidebar/sidebar";

type Props = {
    children: any,
    titlePage?: string
    titleHeader?: string
}

export default function LayoutAdmin(props: Props) {
    return (
        <>
            <Head>
                <title>{props.titlePage ? props.titlePage : 'Dashboard | Passe escolar'}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <SideBar />
            <div className="bg-slate-100 relative md:ml-64 ">
                <div className="bg-slate-700 h-96 px-20 py-9">
                    <Header title={`${props.titleHeader ? props.titleHeader : 'Dashboard'}`} />
                    <InfoDashBoard />
                </div>
                <div className="px-20 py-9">
                    {props.children}
                    <Footer />
                </div>
            </div>
        </>
    )
}